version: 2

sources:
    - name: jaffle_shop
      description: This is a replica of the Postgres database used by our app
      database: raw
      schema: jaffle_shop
      tables:
          - name: customers
            description: One record per customer.
          - name: orders
            loaded_at_field: _ETL_LOADED_AT
            description: One record per order. Includes cancelled and deleted orders.
            freshness: 
              error_after:
                count: 15
                period: day
              warn_after:
                count: 1
                period: day
            